dist: focal
os: linux
language: shell

env:
  VCS_REF=`git rev-parse --short HEAD`
  BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  DOCKER_IMAGE=binhnx285/helm-kubectl
  DOCKER_TAG_MAJOR=1
  TAG_LATEST=true
  DOCKER_TAG=1.0.0
  KUBE_VERSION=1.20.4

services:
  - docker

script:
  # Base Docker Image
  - | 
    docker build --build-arg VCS_REF=$VCS_REF \
                 --build-arg BUILD_DATE=$BUILD_DATE \
                 --build-arg KUBE_VERSION=$KUBE_VERSION \
                 --build-arg HELM_VERSION=$DOCKER_TAG \
                 -t $DOCKER_IMAGE:$DOCKER_TAG .
  # Build LATEST tag if enabled
  - if $TAG_LATEST ; then docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest; fi
  
  # Build major version tag
  - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:$DOCKER_TAG_MAJOR

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:$DOCKER_TAG_MAJOR
  - if $TAG_LATEST ; then docker push $DOCKER_IMAGE:latest; fi